Fix RepositoryIntegrationTest when running tests with eap7 container profile (#828)
When run with -Peap7,(kie-wb|kie-drools-wb) this test was failing with

```
org.kie.wb.test.rest.client.ClientRequestTimedOutException: SERVER_ERROR: Request failed because of GenericPortableException: java.lang.RuntimeException: org.uberfire.java.nio.fs.jgit.util.commands.Clone$CloneException: Error cloning origin <git://localhost:/testSpace/repoToBeCloned>.
....
at org.kie.wb.test.rest.functional.RepositoryIntegrationTest.testCloneRepositoryInternal(RepositoryIntegrationTest.java:84)
```

Because the property the org.uberfire.nio.git.daemon.port wasn't initialized properly via container cargo configuration.